# DeepSeek API ??
deepseek.api.base-url=https://api.deepseek.com/v1
deepseek.api.key=${DEEPSEEK_API_KEY}
deepseek.model=deepseek-chat

# Aiven MySQL ???????
spring.datasource.url=jdbc:mysql://mysql-391ac3b4-dicky0715-ea7c.a.aivencloud.com:23103/defaultdb?useSSL=true&serverTimezone=Asia/Hong_Kong
spring.datasource.username=avnadmin
spring.datasource.password={AVNS_E11X6nOy2Wa6JGU_CJb}

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect